# Generated by Django 4.2 on 2024-02-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='icons/')),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес магазина', 'verbose_name_plural': 'Адреса магазинов'},
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Адрес магазина'),
        ),
    ]
