# Generated by Django 4.2 on 2024-04-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Обратную связь  ', 'verbose_name_plural': 'Обратная связь'},
        ),
    ]
