# Generated by Django 4.2 on 2024-04-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='product',
        ),
    ]
